window.additionalWatches = [
  {key:'submariner-no-date',id:11,brand:'Rolex',name:'Submariner No-Date 124060',price:13500,condition:'Excellent condition',year:'2023',image:'image/rolex submariner bezel 2023.jpeg',summary:'Black ceramic bezel · 2023'},
  {key:'datejust-blue',id:12,brand:'Rolex',name:'Datejust 41 Blue Dial',price:11200,condition:'New / unworn',year:'2024',image:'image/rolex blue dial 2024.jpeg',summary:'Jubilee bracelet · 2024'},
  {key:'daytona',id:13,brand:'Rolex',name:'Cosmograph Daytona 116500LN',price:29500,condition:'Excellent condition',year:'2022',image:'image/rolex cosmograp black ceramic bezel 2024.jpeg',summary:'Black ceramic bezel · 2022'},
  {key:'yacht-master',id:14,brand:'Rolex',name:'Yacht-Master 40',price:16800,condition:'Excellent condition',year:'2021',image:'image/rolex yacht master 40 bracelet 2021.jpeg',summary:'Oysterflex bracelet · 2021'},
  {key:'explorer',id:15,brand:'Rolex',name:'Explorer 36',price:8900,condition:'New / unworn',year:'2024',image:'image/rolex explorer 36 bracelet 2024.jpeg',summary:'Oyster bracelet · 2024'},
  {key:'aquanaut',id:16,brand:'Patek Philippe',name:'Aquanaut 5167A',price:42500,condition:'Excellent condition',year:'2022',image:'image/patek philippe aquanaut 5167a.jpeg',summary:'Tropical strap · 2022'},
  {key:'grand-complications',id:17,brand:'Patek Philippe',name:'Annual Calendar 5396R',price:39500,condition:'Excellent condition',year:'2021',image:'image/patek philippe annual calendar 5396r.jpeg',summary:'Rose gold · 2021'},
  {key:'world-time',id:18,brand:'Patek Philippe',name:'World Time 5230G',price:47200,condition:'New / unworn',year:'2023',image:'image/patek philippe world time 5230G.jpeg',summary:'Blue dial · 2023'},
  {key:'nautilus-5726',id:19,brand:'Patek Philippe',name:'Nautilus Annual Calendar 5726A',price:68500,condition:'Excellent condition',year:'2020',image:'image/patek philippe nautilus annual calendar.jpeg',summary:'Moon phase · 2020'},
  {key:'royal-oak-chronograph',id:20,brand:'Audemars Piguet',name:'Royal Oak Chronograph 26331ST',price:38500,condition:'Excellent condition',year:'2022',image:'image/audemars piguet royal oak chronograph 26331ST.jpeg',summary:'Blue dial · 2022'},
  {key:'royal-oak-offshore',id:21,brand:'Audemars Piguet',name:'Royal Oak Offshore Diver',price:24500,condition:'Excellent condition',year:'2021',image:'image/Audemars piguet royal oak offshore diver.jpeg',summary:'Black ceramic · 2021'},
  {key:'code-1159',id:22,brand:'Audemars Piguet',name:'Code 11.59 Selfwinding',price:18500,condition:'New / unworn',year:'2024',image:'image/Audemars piguet code 11.59 selfwinding.jpeg',summary:'Blue dial · 2024'},
  {key:'rm-011',id:23,brand:'Richard Mille',name:'RM 011 Automatic Flyback',price:185000,condition:'Excellent condition',year:'2019',image:'image/Richard mille RM 011 automatic flyback.jpeg',summary:'Titanium case · 2019'},
  {key:'rm-035',id:24,brand:'Richard Mille',name:'RM 035 Bubba Watson',price:145000,condition:'Excellent condition',year:'2020',image:'image/Richard Mille RM 035 Bubba Watson.jpeg',summary:'Quartz TPT case · 2020'},
  {key:'rm-055',id:25,brand:'Richard Mille',name:'RM 055 Bubba Watson',price:225000,condition:'New / unworn',year:'2023',image:'image/Richard Mille RM 055 Bubba Watson.jpeg',summary:'Ceramic case · 2023'},
  {key:'rm-67-01',id:26,brand:'Richard Mille',name:'RM 67-01 Automatic Extra Flat',price:155000,condition:'Excellent condition',year:'2021',image:'image/Richard Mille RM 67-01 Automatic Extra Flat.jpeg',summary:'Titanium · 2021'},
  {key:'rm-07',id:27,brand:'Richard Mille',name:'RM 07-01 Ladies Automatic',price:128000,condition:'New / unworn',year:'2024',image:'image/Richard Mille RM 07-01 Ladies Automatic.jpeg',summary:'Ceramic and diamonds · 2024'},
  {key:'overseas-dual',id:28,brand:'Vacheron Constantin',name:'Overseas Dual Time 7900V',price:34500,condition:'Excellent condition',year:'2022',image:'image/Vacheron Constantin Overseas Dual Time 7900V.jpeg',summary:'Blue dial · 2022'},
  {key:'patrimony',id:29,brand:'Vacheron Constantin',name:'Patrimony Self-Winding',price:19500,condition:'New / unworn',year:'2023',image:'image/Vacheron Constantin Patrimony Self-Winding.jpeg',summary:'Rose gold · 2023'},
  {key:'historiques',id:30,brand:'Vacheron Constantin',name:'Historiques American 1921',price:42500,condition:'Excellent condition',year:'2021',image:'image/Vacheron Constantin Historiques American 1921.jpeg',summary:'White gold · 2021'},
  {key:'tank-must',id:31,brand:'Cartier',name:'Tank Must Large',price:3650,condition:'New / unworn',year:'2024',image:'image/Cartier Tank Must Large.jpeg',summary:'Black leather strap · 2024'},
  {key:'panthere',id:32,brand:'Cartier',name:'Panthere de Cartier Medium',price:7200,condition:'Excellent condition',year:'2022',image:'image/Cartier Panthere de Cartier.jpeg',summary:'Steel and gold · 2022'},
  {key:'ballon-bleu',id:33,brand:'Cartier',name:'Ballon Bleu 36mm',price:6800,condition:'Excellent condition',year:'2021',image:'image/Cartier Ballon Bleu 36mm.jpeg',summary:'Steel bracelet · 2021'},
  {key:'seamaster',id:34,brand:'Omega',name:'Seamaster Diver 300M',price:5900,condition:'New / unworn',year:'2024',image:'image/Omega Seamaster Diver.jpeg',summary:'Blue ceramic bezel · 2024'},
  {key:'moonphase',id:35,brand:'Omega',name:'Speedmaster Moonphase',price:9800,condition:'Excellent condition',year:'2022',image:'image/Omega Speedmaster Moonphase 2022.jpeg',summary:'Moon phase · 2022'},
  {key:'constellation',id:36,brand:'Omega',name:'Constellation Co-Axial 41mm',price:7600,condition:'Excellent condition',year:'2023',image:'image/Omega Constellation Co-Axial 41mm Steel and Sedna gold · 2023.jpeg',summary:'Steel and Sedna gold · 2023'},
  {key:'black-bay-gmt',id:37,brand:'Tudor',name:'Black Bay GMT',price:4850,condition:'Excellent condition',year:'2022',image:'image/Tudor Black Bay GMT opaline dial 2022.jpeg',summary:'Opaline dial · 2022'},
  {key:'pelagos',id:38,brand:'Tudor',name:'Pelagos 39',price:4300,condition:'New / unworn',year:'2024',image:'image/Tudor Pelagos 39 Titanium case · 2024.jpeg',summary:'Titanium case · 2024'},
  {key:'ranger',id:39,brand:'Tudor',name:'Ranger 39',price:3200,condition:'Excellent condition',year:'2023',image:'image/Tudor Ranger 39 Fabric strap · 2023.jpeg',summary:'Fabric strap · 2023'},
  {key:'portugieser-7day',id:40,brand:'IWC',name:'Portugieser Automatic 7 Days',price:12800,condition:'Excellent condition',year:'2022',image:'image/IWC Portugieser Automatic 7 Days silver dial 2022.jpeg',summary:'Silver dial · 2022'},
  {key:'pilot-big-pilot',id:41,brand:'IWC',name:'Big Pilot 43',price:10500,condition:'New / unworn',year:'2024',image:'image/IWC Big Pilot 43.jpeg',summary:'Blue dial · 2024'},
  {key:'ingenieur',id:42,brand:'IWC',name:'Ingenieur Automatic 40',price:11800,condition:'Excellent condition',year:'2023',image:'image/Ingenieur Automatic 40  Integrated bracelet · 2023.jpeg',summary:'Integrated bracelet · 2023'},
  {key:'reverso',id:43,brand:'Jaeger-LeCoultre',name:'Reverso Tribute Small Seconds',price:11200,condition:'Excellent condition',year:'2022',image:'image/Jaeger-LeCoultre Reverso Tribute Small Seconds.jpeg',summary:'Blue dial · 2022'},
  {key:'master-ultra',id:44,brand:'Jaeger-LeCoultre',name:'Master Ultra Thin Moon',price:13800,condition:'New / unworn',year:'2024',image:'image/Jaeger-LeCoultre Master Ultra Thin Moon.jpeg',summary:'Moon phase · 2024'},
  {key:'lange-1',id:45,brand:'A. Lange & Sohne',name:'Lange 1',price:48500,condition:'Excellent condition',year:'2020',image:'image/A. Lange & Sohne Lange 1 Rose gold 2020.jpeg',summary:'Rose gold · 2020'},
  {key:'royal-oak-perpetual',id:46,brand:'Audemars Piguet',name:'Royal Oak Perpetual Calendar',price:118000,condition:'Excellent condition',year:'2021',image:'image/Audemars Piguet Royal Oak Perpetual Calendar.jpeg',summary:'Blue dial · 2021'},
  {key:'zenith-el-primero',id:47,brand:'Zenith',name:'Chronomaster Sport',price:11500,condition:'New / unworn',year:'2024',image:'image/Zenith Chronomaster Sport tri color register 2024.jpeg',summary:'Tri-color registers · 2024'},
  {key:'breguet-marine',id:48,brand:'Breguet',name:'Marine 5517',price:22500,condition:'Excellent condition',year:'2022',image:'image/Breguet Marine 5517.jpeg',summary:'Titanium case · 2022'},
  {key:'hublot-big-bang',id:49,brand:'Hublot',name:'Big Bang Unico',price:18500,condition:'Excellent condition',year:'2021',image:'image/Hublot Big Bang Unico Ceramic case · 2021.jpeg',summary:'Ceramic case · 2021'},
  {key:'girard-perregaux',id:50,brand:'Girard-Perregaux',name:'Laureato 42mm',price:9800,condition:'New / unworn',year:'2024',image:'image/Girard-Perregaux Laureato 42mm blue dial 2024.jpeg',summary:'Blue dial · 2024'},
  {key:'blancpain-fifty',id:51,brand:'Blancpain',name:'Fifty Fathoms Automatique',price:14500,condition:'Excellent condition',year:'2022',image:'image/Blancpain Fifty Fathoms Automatique.jpeg',summary:'Black dial · 2022'},
  {key:'breitling-navitimer',id:52,brand:'Breitling',name:'Navitimer B01 Chronograph',price:8900,condition:'Excellent condition',year:'2023',image:'image/Breitling Navitimer B01 Chronograph.jpeg',summary:'Steel bracelet · 2023'}
];

window.watchCatalog = {};
window.additionalWatches.forEach((watch) => { window.watchCatalog[watch.key] = watch; });
